mydata <- read.csv("C:/Users//shree/OneDrive/Desktop/Downloaded Data Science//Salary_Data.csv")
View(mydata)
colnames(mydata)
attach(mydata)
summary(mydata)
var(Salary)
sd(YearsExperience)
skewness(Salary)
kurtosis(YearsExperience)
plot(mydata)
boxplot(Salary)
boxplot(Salary, horizontal = TRUE)
hist(YearsExperience)
qqnorm(YearsExperience)
cor(mydata)
model <- lm(Salary~YearsExperience)
summary(model)
confint(model,level = 0.95)
model_log<-lm(Salary~log(YearsExperience))  
summary(model_log)
confint(model_log,level=0.95)
model_exp<-lm(log(Salary)~YearsExperience) 
summary(model_exp)
model_final <- predict(model)
model_final
rmse <- sqrt(mean((model_final-Salary)^2))
rmse
plot(model)
hist(residuals(model)) 

