Q2 <- read.csv("C:/Users/shree/OneDrive/Desktop/Downloaded Data Science//delivery_time.csv")
attach(Q2)
View(Q2)
summary(Delivery.Time)
summary(Sorting.Time)
var(Sorting.Time)
var(Delivery.Time)
sd(Sorting.Time)
sd(Delivery.Time)
install.packages("moments")
library(moments)
skewness(Delivery.Time)
kurtosis((Delivery.Time))
barplot(Delivery.Time)
boxplot(Delivery.Time,horizontal = T)
hist(Delivery.Time)
qqnorm(Delivery.Time)
qqline(Delivery.Time)
skewness(Sorting.Time)
kurtosis(Sorting.Time)
barplot(Sorting.Time)
hist(Sorting.Time)
boxplot(Sorting.Time,horizontal = T )
qqnorm(Sorting.Time)
qqline(Sorting.Time)
cor(Q2$Delivery.Time,Q2$Sorting.Time)
plot(Q2)
Model2 <- lm(Delivery.Time ~ Sorting.Time)
summary(Model2)
Model2t <- lm(log(Delivery.Time) ~ log(Sorting.Time))
summary(Model2t)
model_final <- predict(Model2t)
model_final
rmse <- sqrt(mean((model_final-Delivery.Time)^2))
rmse
plot(Model2t)
return()
